### ISSUE TITLE
Question: How is this intended to be used?

### ISSUE THREAD

**Issue by mwarger** [omar-dulaimi/prisma-trpc-shield-generator#2]
I'm curious how this generator is meant to be used.  Is it meant to provide a head start for the boilerplate needed to work with something like Prisma tRPC Generator?

I just wanted to clarify, since this will overwrite anything defined in the shield every time it's generated.  This would obviously overwrite any rule customization that's been done.  Is this meant be copy-pasted elsewhere for use in the application?

Thanks!

**Comment by omar-dulaimi** [comment]
It's as you described, for now at least. We can improve this further. I don't like how rules get removed after each generation, so maybe we could do something about that soon.
